---

# This keeps ansible from complaining if no other variables are defined
dummy:

#
# Email of the admin responsible for this GCS installation. This value is
# used to register for the LetsEncrypt SSL certificate(s) pulled during
# installation.
#
admin_email: jasonalt@globus.org

#
# All users who access this POD, other than anonymous access, must have an
# acocunt from this domain linked with home institution account.
#
idp_domain: globusid.org

#
# This user is granted the 'endpoint manager' role during installation. This
# allows the shared Globus account 'osn@globusid.org' to manage all OSN 
# endpoints via the Globus Web and CLI interfaces.
#
endpoint_admin: osn@globusid.org

#
# Location of Ceph RadosGW. SSL is not necessary if the service runs locally.
# Ideally, have one radosgw and Globus Connect Server pair per monitor node.
ceph_url: http://localhost:3000

#
# This is an administrative account created on the Ceph cluster during
# installation. Globus Connect Server uses this account to query Ceph
# for available Ceph accounts when Globus is determing how to map a user's home
# institution credential to a ceph account.
#
globus_admin_user: globus_admin

#
# List of accounts from 'idp_domain' listed above that are allowed to create
# Globus collections in Ceph. To simplify deployment and keep account management
# minimal, limit the number of users listed in. Then configure a collection to
# permit additional users via the globus.org web interface or CLI.
# These users must already exist in Ceph, this playbook will not create these
# accounts.
ceph_allowed_users: osn
